### PR TITLE
Translation strings for MacOS support

### PR DESCRIPTION
**Pull request by emassey0135**
This adds en_us translation strings for the speech settings config menu button and screen title, the speech rate button in this menu, and the warning message about the accessibility permission being disabled on MacOS. Unfortunately I am not fluent in any other language, so I cannot contribute the rest of the needed strings.

### CODE REVIEW

**Comment by khanshoaib3** [comment]
@boholder Will you be adding chinese translation in this pr itself?

**Comment by boholder** [comment]
> @boholder Will you be adding chinese translation in this pr itself?

Oh, yep, left it to me, ~I'll send a git patch to Elijah~ so the maintainer can push commits to others PR, it's convenient.

**Comment by khanshoaib3** [comment]
> so the maintainer can push commits to others PR, it's convenient.

Yup, I do that all the time :)

**Comment by khanshoaib3** [comment]
\[Fast Forward CI\] macos merged into main... Pushed the changes to origin.

**Pull request merged**
